In [2]:
import numpy as np;
import pandas as pd;
import seaborn as sns;
import matplotlib.pyplot as plt;
import warnings 
warnings.filterwarnings('ignore');

In [3]:
df=pd.read_csv(r'D:\ML\machne\fordcar.csv')

In [4]:
df.shape

(17966, 9)

In [5]:
df.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [6]:
df.head()

     model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [7]:
df.tail()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
17961,B-MAX,2017,8999,Manual,16700,Petrol,150,47.1,1.4
17962,B-MAX,2014,7499,Manual,40700,Petrol,30,57.7,1.0
17963,Focus,2015,9999,Manual,7010,Diesel,20,67.3,1.6
17964,KA,2018,8299,Manual,5007,Petrol,145,57.7,1.2
17965,Focus,2015,8299,Manual,5007,Petrol,22,57.7,1.0

In [8]:
cos=df.columns
for co in cos:
    print('\n',co)
    print(df[co].value_counts())

 model
model
 Fiesta                   6557
 Focus                    4588
 Kuga                     2225
 EcoSport                 1143
 C-MAX                     543
 Ka+                       531
 Mondeo                    526
 B-MAX                     355
 S-MAX                     296
 Grand C-MAX               247
 Galaxy                    228
 Edge                      208
 KA                        199
 Puma                       80
 Tourneo Custom             69
 Grand Tourneo Connect      59
 Mustang                    57
 Tourneo Connect            33
 Fusion                     16
 Streetka                    2
 Ranger                      1
 Escort                      1
 Transit Tourneo             1
Focus                        1
Name: count, dtype: int64

 year
year
2017    4888
2018    4014
2019    3194
2016    2331
2015    1368
2014     805
2013     609
2020     258
2012     115
2011      94
2009      91
2010      67
2008      57
2007      32
2005      16
2006      13
2004       4
2003       3
2002       3
1998       1
1996       1
2000       1
2060       1
Name: count, dtype: int64

 price
price
10000    164
11000    153
10500    148
12000    126
9000     118
        ...
4170       1
5465       1
1500       1
3200       1
2900       1
Name: count, Length: 3511, dtype: int64

 transmission
transmission
Manual       15518
Automatic     1361
Semi-Auto     1087
Name: count, dtype: int64

 mileage
mileage
10       40
15000    38
25000    34
10000    32
6000     31
         ..
5046      1
1779      1
10452     1
9725      1
9264      1
Name: count, Length: 13528, dtype: int64

 fuelType
fuelType
Petrol      12179
Diesel       5762
Hybrid         22
Electric        2
Other           1
Name: count, dtype: int64

 tax
tax
145    8944
0      2153
150    1944
125    1407
30     1236
20     1210
160     358
200     252
235     123
165     113
205      60
260      41
240      32
265      15
300      11
135      10
140       8
570       6
195       6
325       6
555       4
220       3
155       3
115       3
580       2
120       2
230       2
190       2
305       2
330       2
110       1
270       1
210       1
185       1
290       1
22        1
Name: count, dtype: int64

 mpg
mpg
65.7    2528
54.3    1774
60.1    1674
64.2     995
57.7     962
        ...
69.0       1
28.0       1
54.2       1
28.5       1
23.9       1
Name: count, Length: 90, dtype: int64

 engineSize
engineSize
1.0    7765
1.5    3418
2.0    3311
1.2    1626
1.6     923
1.1     559
1.4     112
2.3      80
0.0      51
5.0      45
1.8      35
2.2      13
2.5      13
1.3      13
3.2       1
1.7       1
Name: count, dtype: int64

In [9]:
df=pd.get_dummies(df,columns=['transmission','fuelType','model'])

In [10]:
df.drop_duplicates(inplace=True)
df.shape
df.columns

Index(['year', 'price', 'mileage', 'tax', 'mpg', 'engineSize',
       'transmission_Automatic', 'transmission_Manual',
       'transmission_Semi-Auto', 'fuelType_Diesel', 'fuelType_Electric',
       'fuelType_Hybrid', 'fuelType_Other', 'fuelType_Petrol', 'model_ B-MAX',
       'model_ C-MAX', 'model_ EcoSport', 'model_ Edge', 'model_ Escort',
       'model_ Fiesta', 'model_ Focus', 'model_ Fusion', 'model_ Galaxy',
       'model_ Grand C-MAX', 'model_ Grand Tourneo Connect', 'model_ KA',
       'model_ Ka+', 'model_ Kuga', 'model_ Mondeo', 'model_ Mustang',
       'model_ Puma', 'model_ Ranger', 'model_ S-MAX', 'model_ Streetka',
       'model_ Tourneo Connect', 'model_ Tourneo Custom',
       'model_ Transit Tourneo', 'model_Focus'],
      dtype='object')

In [11]:
boo=['transmission_Automatic', 'transmission_Manual','transmission_Semi-Auto', 'fuelType_Diesel', 'fuelType_Electric','transmission_Semi-Auto', 'fuelType_Diesel', 'fuelType_Electric','fuelType_Hybrid', 'fuelType_Other', 'fuelType_Petrol','model_ B-MAX','model_ C-MAX', 'model_ EcoSport', 'model_ Edge', 'model_ Escort','model_ Fiesta', 'model_ Focus', 'model_ Fusion', 'model_ Galaxy','model_ Grand C-MAX', 'model_ Grand Tourneo Connect', 'model_ KA','model_ Ka+', 'model_ Kuga', 'model_ Mondeo', 'model_ Mustang','model_ Puma', 'model_ Ranger', 'model_ S-MAX', 'model_ Streetka','model_ Tourneo Connect', 'model_ Tourneo Custom',
'model_ Transit Tourneo', 'model_Focus']
for co in boo:
    df[co]=df[co].astype(int)

In [12]:
df.head()

,year,price,mileage,tax,mpg,engineSize,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,...,model_ Mondeo,model_ Mustang,model_ Puma,model_ Ranger,model_ S-MAX,model_ Streetka,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus
0,2017,12000,15944,150,57.7,1.0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2018,14000,9083,150,57.7,1.0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2017,13000,12456,150,57.7,1.0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2019,17500,10460,145,40.3,1.5,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2019,16500,1482,145,48.7,1.0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
df.corr(numeric_only=True)

,year,price,mileage,tax,mpg,engineSize,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,...,model_ Mondeo,model_ Mustang,model_ Puma,model_ Ranger,model_ S-MAX,model_ Streetka,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus
year,1.000000,0.635715,-0.708690,0.297183,-0.021702,-0.137582,0.036475,-0.037490,0.013433,-0.088940,...,-0.070172,0.037709,0.074060,-0.014104,-0.023309,-0.058679,0.001553,0.025323,-0.010452,-0.006801
price,0.635715,1.000000,-0.530483,0.405969,-0.346263,0.411451,0.207964,-0.258201,0.140648,0.199033,...,-0.000385,0.267520,0.129067,0.003521,0.147319,-0.023147,0.014268,0.117139,0.000285,-0.006282
mileage,-0.708690,-0.530483,1.000000,-0.257543,0.117697,0.214692,-0.049923,0.058845,-0.029242,0.257338,...,0.196700,-0.040561,-0.067131,0.024934,0.057835,0.024637,0.002588,-0.005105,-0.001499,-0.007090
tax,0.297183,0.405969,-0.257543,1.000000,-0.502343,0.185358,0.154974,-0.181935,0.089715,-0.128538,...,-0.036682,0.088872,0.037361,0.015302,0.077500,0.028475,-0.001412,0.051303,0.014698,-0.011030
mpg,-0.021702,-0.346263,0.117697,-0.502343,1.000000,-0.262239,-0.234934,0.302342,-0.174245,0.292856,...,0.032659,-0.188096,-0.051222,-0.021896,-0.076811,-0.023384,0.000212,-0.118765,-0.011617,-0.000154
engineSize,-0.137582,0.411451,0.214692,0.185358,-0.262239,1.000000,0.164279,-0.225529,0.142181,0.640925,...,0.215458,0.397355,-0.053515,0.032035,0.182153,0.006109,0.014037,0.094870,0.014713,-0.006074
transmission_Automatic,0.036475,0.207964,-0.049923,0.154974,-0.234934,0.164279,1.000000,-0.721818,-0.072692,0.057771,...,0.104062,0.070015,-0.019144,-0.002149,0.054287,-0.003040,0.037855,0.009395,-0.002149,-0.002149
transmission_Manual,-0.037490,-0.258201,0.058845,-0.181935,0.302342,-0.225529,-0.721818,1.000000,-0.637782,-0.098477,...,-0.083398,-0.093347,0.026523,0.002977,-0.087193,0.004211,-0.021773,0.003712,0.002977,0.002977
transmission_Semi-Auto,0.013433,0.140648,-0.029242,0.089715,-0.174245,0.142181,-0.072692,-0.637782,1.000000,0.077620,...,0.004373,0.056602,-0.016916,-0.001899,0.065237,-0.002686,-0.010752,-0.015804,-0.001899,-0.001899
fuelType_Diesel,-0.088940,0.199033,0.257338,-0.128538,0.292856,0.640925,0.057771,-0.098477,0.077620,1.000000,...,0.179291,-0.038899,-0.045823,0.010914,0.157534,-0.007275,0.056111,0.090833,0.010914,-0.005144
fuelType_Electric,-0.004454,0.007759,-0.003502,-0.019357,0.009822,0.015908,0.036946,-0.026668,-0.002686,-0.007275,...,0.061599,-0.000600,-0.000707,-0.000079,-0.001373,-0.000112,-0.000450,-0.000661,-0.000079,-0.000079
fuelType_Hybrid,0.024170,0.073356,-0.001411,-0.007162,0.107118,0.054639,0.104509,-0.083840,0.004512,-0.024143,...,0.147015,-0.001993,0.021708,-0.000263,-0.004556,-0.000373,-0.001492,-0.002193,-0.000263,-0.000263
fuelType_Other,-0.006801,0.002421,-0.001509,-0.013687,0.006945,0.011249,0.026124,-0.018857,-0.001899,-0.005144,...,0.043556,-0.000425,-0.000500,-0.000056,-0.000971,-0.000079,-0.000318,-0.000467,-0.000056,-0.000056
fuelType_Petrol,0.087231,-0.204534,-0.256832,0.129587,-0.300907,-0.644836,-0.066819,0.105574,-0.077779,-0.996786,...,-0.192233,0.039025,0.044163,-0.010879,-0.156963,0.007299,-0.055919,-0.090541,-0.010879,0.005161
model_ B-MAX,-0.094983,-0.119506,0.035588,-0.051222,-0.031376,-0.010584,-0.003977,-0.049824,0.076227,-0.030446,...,-0.024356,-0.008022,-0.009450,-0.001061,-0.018341,-0.001500,-0.006006,-0.008829,-0.001061,-0.001061
model_ C-MAX,-0.078755,-0.088128,0.046377,-0.118536,0.027674,0.023169,0.005919,-0.005799,0.001769,0.101832,...,-0.030477,-0.010038,-0.011824,-0.001327,-0.022950,-0.001877,-0.007516,-0.011048,-0.001327,-0.001327
model_ EcoSport,0.084409,0.010959,-0.091369,0.096336,-0.123400,-0.144822,-0.021467,0.002478,0.020319,-0.103801,...,-0.044711,-0.014726,-0.017347,-0.001947,-0.033669,-0.002754,-0.011026,-0.016207,-0.001947,-0.001947
model_ Edge,0.024422,0.237867,-0.007716,0.075649,-0.124373,0.161985,0.084243,-0.154978,0.129585,0.157170,...,-0.018563,-0.006114,-0.007202,-0.000809,-0.013979,-0.001143,-0.004578,-0.006729,-0.000809,-0.000809
model_ Escort,-0.076181,-0.014665,0.010271,0.018322,-0.017385,0.007784,-0.002149,0.002977,-0.001899,-0.005144,...,-0.001289,-0.000425,-0.000500,-0.000056,-0.000971,-0.000079,-0.000318,-0.000467,-0.000056,-0.000056
model_ Fiesta,-0.021439,-0.333063,-0.065318,-0.152642,0.231046,-0.443120,-0.135839,0.142216,-0.053772,-0.423291,...,-0.130549,-0.042997,-0.050650,-0.005686,-0.098309,-0.008042,-0.032194,-0.047323,-0.005686,-0.005686
model_ Focus,0.037677,0.112554,0.011668,-0.020454,0.125924,0.014581,0.032895,0.018059,-0.062634,0.038011,...,-0.100840,-0.033212,-0.039124,-0.004392,-0.075937,-0.006212,-0.024867,-0.036554,-0.004392,-0.004392
model_ Fusion,-0.128589,-0.061498,0.065637,0.034046,-0.037035,0.009488,0.019684,-0.009928,-0.007599,-0.008537,...,-0.005158,-0.001699,-0.002001,-0.000225,-0.003884,-0.000318,-0.001272,-0.001870,-0.000225,-0.000225
model_ Galaxy,-0.026042,0.133839,0.056198,0.059768,-0.051298,0.164777,0.033511,-0.067154,0.059480,0.153692,...,-0.019546,-0.006438,-0.007583,-0.000851,-0.014719,-0.001204,-0.004820,-0.007085,-0.000851,-0.000851
model_ Grand C-MAX,-0.033694,-0.034752,0.027490,-0.077384,0.005366,0.015534,0.022144,-0.020029,0.004219,0.093501,...,-0.020400,-0.006719,-0.007915,-0.000889,-0.015362,-0.001257,-0.005031,-0.007395,-0.000889,-0.000889
model_ Grand Tourneo Connect,0.009128,0.029859,0.002397,-0.000224,0.012891,0.020945,0.036259,-0.018037,-0.014360,0.082530,...,-0.009747,-0.003210,-0.003782,-0.000425,-0.007340,-0.000600,-0.002404,-0.003533,-0.000425,-0.000425
model_ KA,-0.144641,-0.157703,0.065690,-0.098073,-0.018485,-0.044642,-0.030333,0.042023,-0.026801,-0.070303,...,-0.018193,-0.005992,-0.007059,-0.000792,-0.013700,-0.001121,-0.004486,-0.006595,-0.000792,-0.000792
model_ Ka+,0.085241,-0.131120,-0.105624,0.061122,-0.077850,-0.064022,-0.049887,0.069113,-0.044079,-0.118695,...,-0.029921,-0.009855,-0.011609,-0.001303,-0.022532,-0.001843,-0.007379,-0.010846,-0.001303,-0.001303
model_ Kuga,0.047974,0.281926,0.006465,0.196326,-0.231684,0.398110,0.061812,-0.085832,0.054901,0.377775,...,-0.064713,-0.021314,-0.025108,-0.002819,-0.048732,-0.003986,-0.015958,-0.023458,-0.002819,-0.002819
model_ Mondeo,-0.070172,-0.000385,0.196700,-0.036682,0.032659,0.215458,0.104062,-0.083398,0.004373,0.179291,...,1.000000,-0.009747,-0.011482,-0.001289,-0.022287,-0.001823,-0.007298,-0.010728,-0.001289,-0.001289
model_ Mustang,0.037709,0.267520,-0.040561,0.088872,-0.188096,0.397355,0.070015,-0.093347,0.056602,-0.038899,...,-0.009747,1.000000,-0.003782,-0.000425,-0.007340,-0.000600,-0.002404,-0.003533,-0.000425,-0.000425
model_ Puma,0.074060,0.129067,-0.067131,0.037361,-0.051222,-0.053515,-0.019144,0.026523,-0.016916,-0.045823,...,-0.011482,-0.003782,1.000000,-0.000500,-0.008647,-0.000707,-0.002832,-0.004162,-0.000500,-0.000500
model_ Ranger,-0.014104,0.003521,0.024934,0.015302,-0.021896,0.032035,-0.002149,0.002977,-0.001899,0.010914,...,-0.001289,-0.000425,-0.000500,1.000000,-0.000971,-0.000079,-0.000318,-0.000467,-0.000056,-0.000056
model_ S-MAX,-0.023309,0.147319,0.057835,0.077500,-0.076811,0.182153,0.054287,-0.087193,0.065237,0.157534,...,-0.022287,-0.007340,-0.008647,-0.000971,1.000000,-0.001373,-0.005496,-0.008079,-0.000971,-0.000971
model_ Streetka,-0.058679,-0.023147,0.024637,0.028475,-0.023384,0.006109,-0.003040,0.004211,-0.002686,-0.007275,...,-0.001823,-0.000600,-0.000707,-0.000079,-0.001373,1.000000,-0.000450,-0.000661,-0.000079,-0.000079
model_ Tourneo Connect,0.001553,0.014268,0.002588,-0.001412,0.000212,0.014037,0.037855,-0.021773,-0.010752,0.056111,...,-0.007298,-0.002404,-0.002832,-0.000318,-0.005496,-0.000450,1.000000,-0.002646,-0.000318,-0.000318
model_ Tourneo Custom,0.025323,0.117139,-0.005105,0.051303,-0.118765,0.094870,0.009395,0.003712,-0.015804,0.090833,...,-0.010728,-0.003533,-0.004162,-0.000467,-0.008079,-0.000661,-0.002646,1.000000,-0.000467,-0.000467
model_ Transit Tourneo,-0.010452,0.000285,-0.001499,0.014698,-0.011617,0.014713,-0.002149,0.002977,-0.001899,0.010914,...,-0.001289,-0.000425,-0.000500,-0.000056,-0.000971,-0.000079,-0.000318,-0.000467,1.000000,-0.000056
model_Focus,-0.006801,-0.006282,-0.007090,-0.011030,-0.000154,-0.006074,-0.002149,0.002977,-0.001899,-0.005144,...,-0.001289,-0.000425,-0.000500,-0.000056,-0.000971,-0.000079,-0.000318,-0.000467,-0.000056,1.000000

In [14]:
# df=df.drop(columns=['fuelType_Hybrid', 'fuelType_Other', 'fuelType_Petrol','model_ C-MAX','model_ EcoSport', 'model_ Escort','model_ Fusion', 'model_ Focus', 'model_ Galaxy','model_ Grand C-MAX', 'model_ Grand Tourneo Connect','model_ Mondeo','model_ Ranger','model_ Streetka','model_ Tourneo Connect','model_ Transit Tourneo', 'model_Focus'])#

In [15]:
df.columns

Index(['year', 'price', 'mileage', 'tax', 'mpg', 'engineSize',
       'transmission_Automatic', 'transmission_Manual',
       'transmission_Semi-Auto', 'fuelType_Diesel', 'fuelType_Electric',
       'fuelType_Hybrid', 'fuelType_Other', 'fuelType_Petrol', 'model_ B-MAX',
       'model_ C-MAX', 'model_ EcoSport', 'model_ Edge', 'model_ Escort',
       'model_ Fiesta', 'model_ Focus', 'model_ Fusion', 'model_ Galaxy',
       'model_ Grand C-MAX', 'model_ Grand Tourneo Connect', 'model_ KA',
       'model_ Ka+', 'model_ Kuga', 'model_ Mondeo', 'model_ Mustang',
       'model_ Puma', 'model_ Ranger', 'model_ S-MAX', 'model_ Streetka',
       'model_ Tourneo Connect', 'model_ Tourneo Custom',
       'model_ Transit Tourneo', 'model_Focus'],
      dtype='object')

In [16]:
from sklearn.preprocessing import StandardScaler
cos=['year','mileage', 'tax', 'mpg', 'engineSize']
scaler=StandardScaler()
df[cos]=scaler.fit_transform(df[cos])

In [17]:
df.rename(columns={'model_ Ka+':'model_ KA'},inplace=True)

In [18]:
from sklearn.model_selection import train_test_split
x=df.drop('price',axis=1)
y=df['price']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [19]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.8188919779971253

In [20]:
n=x_test.shape[0]
p=x_test.shape[1]
adjr2=1-((1-r2)*(n-1)/(n-p-1))
adjr2

0.8169909859931235